In [3]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [6]:
array_list.dtype

dtype('<U1')

In [7]:
type(list_)

list

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(array_list.dtype)

<U1
<U1
<U1
<U1
<U1


In [14]:
array_list = np.array(object = list_, dtype = int) #it will change the dtype of all the elements to int64

In [15]:
for i in array_list:
    print(array_list.dtype)

int64
int64
int64
int64
int64


In [16]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [25]:
num_array.shape

(2, 3)

In [26]:
num_array.size

6

In [27]:
print(num_array)

[[1 2 3]
 [4 5 6]]


In [28]:
len(num_list)

2

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.